### ISSUE TITLE
Thought on use root user by default

### ISSUE THREAD

**Issue by gengjiawen** [rvagg/node-ci-containers#1]
Root is very convenient in container. 

Also, with current user, looks like I can't use sudo
```console
iojs@041a46c92d7b:~$ sudo apt update
bash: sudo: command not found
```

**Comment by rvagg** [comment]
This is something I want to avoid because `root` also gives you certain privileges on the host, including the filesystem, and is the best way to break out if/when the next escape vector is discovered. By constraining to user `iojs` with no way to escalate privileges we can have more confidence in putting more execution control into nodejs/node where random contributors will show up and edit .ci.yml—the only line of defense against malicious code creeping in there is collaborators reviewing changes carefully, but I'm not super confident in that kind of human-defense.

If you want root in one of the containers locally, just `-u root`, but these are intended to be locked down. *If* we need additional packages in the containers, then we edit the Dockerfiles here or, probably better, introduce another dedicated image with that specific configuration.

**Comment by gengjiawen** [comment]
> This is something I want to avoid because root also gives you certain privileges on the host, including the filesystem

Thanks for the explanation. But I don't think you can access to host filesystem unless you share via --volume options.

**Comment by gengjiawen** [comment]
I think it won't be a issue since I can switch to root.
